window.ANREVIEW_DATA = {
  generatedAt: "2026-04-12",
  sources: [
    { label: "ANU Programs and Courses: Bachelor of Economics", url: "https://programsandcourses.anu.edu.au/program/becon" },
    { label: "ANU Programs and Courses: Econometrics Minor", url: "https://programsandcourses.anu.edu.au/minor/EMET-MIN" },
    { label: "ANU Programs and Courses: Strategy, Behaviour and Economics Minor", url: "https://programsandcourses.anu.edu.au/minor/SBEC-MIN" },
    { label: "ANU Programs and Courses: Bachelor of Laws (Honours)", url: "https://programsandcourses.anu.edu.au/program/allb" },
    { label: "ANU Programs and Courses: Juris Doctor", url: "https://programsandcourses.anu.edu.au/program/mjd" },
    { label: "ANU Law School: Our People", url: "https://law.anu.edu.au/about/our-people" },
    { label: "ANU Research School of Accounting staff directory", url: "https://rsa.anu.edu.au/about/staff-directory" },
    { label: "ANU Research School of Finance, Actuarial Studies and Statistics people", url: "http://rsfas.anu.edu.au/about/people" },
    { label: "ANU Research School of Economics people", url: "https://rse.anu.edu.au/about/people" },
    { label: "ANU Research School of Management people", url: "https://rsm.anu.edu.au/about/people" },
    { label: "ANU Programs and Courses: ECON1101 Microeconomics 1", url: "https://programsandcourses.anu.edu.au/course/ECON1101" },
    { label: "ANU Programs and Courses: ECON1102 Macroeconomics 1", url: "https://programsandcourses.anu.edu.au/course/ECON1102" },
    { label: "ANU Programs and Courses: ECON2014 Managerial Economics", url: "https://programsandcourses.anu.edu.au/course/ECON2014" },
    { label: "ANU Programs and Courses: ECON2101 Microeconomics 2", url: "https://programsandcourses.anu.edu.au/course/ECON2101" },
    { label: "ANU Programs and Courses: ECON2125 Optimisation for Economics and Financial Economics", url: "https://programsandcourses.anu.edu.au/course/ECON2125" },
    { label: "ANU Programs and Courses: ECON3101 Microeconomics 3", url: "https://programsandcourses.anu.edu.au/course/ECON3101" },
    { label: "ANU Programs and Courses: ECON8069 Business Economics", url: "https://programsandcourses.anu.edu.au/course/ECON8069" },
    { label: "ANU Programs and Courses: EMET1001 Foundations of Economic and Financial Models", url: "https://programsandcourses.anu.edu.au/course/EMET1001" },
    { label: "ANU Programs and Courses: MGMT2100 Communication for Business", url: "https://programsandcourses.anu.edu.au/course/MGMT2100" },
    { label: "ANU Programs and Courses: MGMT3015 Corporate Strategy", url: "https://programsandcourses.anu.edu.au/course/MGMT3015" },
    { label: "ANU Programs and Courses: MKTG2004 Introduction to Marketing", url: "https://programsandcourses.anu.edu.au/course/MKTG2004" },
    { label: "ANU Programs and Courses: FINM3005 Corporate Valuation", url: "https://programsandcourses.anu.edu.au/course/FINM3005" }
  ],
  academics: [
    {
      id: "ralf-steinhauser",
      type: "academic",
      name: "Dr Ralf Steinhauser",
      school: "Research School of Economics",
      schoolCode: "RSE",
      position: "Senior Lecturer",
      focus: "Microeconomics, public economics, empirical policy analysis",
      email: "ralf.steinhauser@anu.edu.au",
      office: "ANU CBE staff directory",
      profileUrl: "https://cbe.anu.edu.au/about/staff-directory/",
      tags: ["economics", "micro", "first-year"],
      linkedCourses: ["ECON1101"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "timo-henckel",
      type: "academic",
      name: "Associate Professor Timo Henckel",
      school: "Research School of Economics",
      schoolCode: "RSE",
      position: "Associate Professor",
      focus: "Behavioural macroeconomics, monetary economics, international macroeconomics",
      email: "timo.henckel@anu.edu.au",
      office: "Room 1023, Arndt Bld (25A)",
      profileUrl: "https://cbe.anu.edu.au/about/staff-directory/associate-professor-timo-henckel",
      tags: ["economics", "macro", "policy"],
      linkedCourses: ["ECON1102"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "elena-capatina",
      type: "academic",
      name: "Associate Professor Elena Capatina",
      school: "Research School of Economics",
      schoolCode: "RSE",
      position: "Associate Professor",
      focus: "Macroeconomics, labour economics, health economics",
      email: "elena.capatina@anu.edu.au",
      office: "Room 2011, HW Arndt Bld (25A)",
      profileUrl: "https://cbe.anu.edu.au/about/staff-directory/associate-professor-elena-capatina",
      tags: ["economics", "macro", "labour"],
      linkedCourses: ["ECON1102"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "james-taylor",
      type: "academic",
      name: "Dr James Taylor",
      school: "Research School of Economics",
      schoolCode: "RSE",
      position: "Lecturer",
      focus: "Mathematical economics, game theory, microeconomic theory",
      email: "james.taylor@anu.edu.au",
      office: "Room 1011, HW Arndt Bld (25A)",
      profileUrl: "https://cbe.anu.edu.au/about/staff-directory/dr-james-taylor",
      tags: ["economics", "theory", "quantitative"],
      linkedCourses: ["ECON2101", "ECON2125"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "kieron-meagher",
      type: "academic",
      name: "Professor Kieron Meagher",
      school: "Research School of Economics",
      schoolCode: "RSE",
      position: "Professor",
      focus: "Game theory, political economy, industrial organisation",
      email: "kieron.meagher@anu.edu.au",
      office: "Room 2012, HW Arndt Bld (25A)",
      profileUrl: "https://cbe.anu.edu.au/about/staff-directory/professor-kieron-meagher",
      tags: ["economics", "game theory", "advanced"],
      linkedCourses: ["ECON3101"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "ruitian-lang",
      type: "academic",
      name: "Dr Ruitian Lang",
      school: "Research School of Economics",
      schoolCode: "RSE",
      position: "Lecturer",
      focus: "Game theory, dynamic games, mechanism design",
      email: "ruitian.lang@anu.edu.au",
      office: "Room 2014, HW Arndt Bld (25A)",
      profileUrl: "https://cbe.anu.edu.au/about/staff-directory/dr-ruitian-lang",
      tags: ["economics", "theory", "mechanism design"],
      linkedCourses: ["ECON2125", "ECON8069"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "tina-kao",
      type: "academic",
      name: "Dr Tina Kao",
      school: "Research School of Economics",
      schoolCode: "RSE",
      position: "Senior Lecturer",
      focus: "Industrial organisation, applied microeconomic theory",
      email: "tina.kao@anu.edu.au",
      office: "Room 2015, HW Arndt Bld (25A)",
      profileUrl: "https://cbe.anu.edu.au/about/staff-directory/dr-tina-kao",
      tags: ["economics", "micro", "industrial organisation"],
      linkedCourses: ["EMET1001", "ECON2014"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "marina-iskhakova",
      type: "academic",
      name: "Dr Marina Iskhakova",
      school: "Research School of Economics",
      schoolCode: "RSE",
      position: "Senior Lecturer",
      focus: "International education, cultural intelligence, economics and management",
      email: "marina.iskhakova@anu.edu.au",
      office: "Room 2113, Copland Bld (24)",
      profileUrl: "https://cbe.anu.edu.au/about/staff-directory/dr-marina-iskhakova",
      tags: ["economics", "management", "managerial"],
      linkedCourses: ["ECON2014", "ECON8069"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "rohan-pitchford",
      type: "academic",
      name: "Professor Rohan Pitchford",
      school: "Research School of Economics",
      schoolCode: "RSE",
      position: "Professor",
      focus: "Game theory, law and economics, contract theory",
      email: "rohan.pitchford@anu.edu.au",
      office: "Room 2028, HW Arndt Bld (25A)",
      profileUrl: "https://cbe.anu.edu.au/about/staff-directory/professor-rohan-pitchford",
      tags: ["economics", "theory", "contracts"],
      linkedCourses: ["ECON2101"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "alexander-eapen",
      type: "academic",
      name: "Associate Professor Alexander Eapen",
      school: "Research School of Management",
      schoolCode: "RSM",
      position: "Associate Professor",
      focus: "Strategic management, international business, knowledge spillovers",
      email: "alex.eapen@anu.edu.au",
      office: "Room 2.20, CBE Bld (26C)",
      profileUrl: "https://cbe.anu.edu.au/about/staff-directory/associate-professor-alexander-eapen",
      tags: ["management", "strategy", "business"],
      linkedCourses: ["MGMT3015"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "david-cheng",
      type: "academic",
      name: "Associate Professor David Cheng",
      school: "Research School of Management",
      schoolCode: "RSM",
      position: "Associate Professor",
      focus: "Leadership, management, workplace wellbeing",
      email: "david.cheng@anu.edu.au",
      office: "Room 1046, PAP Moran Bld (26B)",
      profileUrl: "https://cbe.anu.edu.au/about/staff-directory/associate-professor-david-cheng",
      tags: ["management", "leadership", "business"],
      linkedCourses: [],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "katerina-kormusheva",
      type: "academic",
      name: "Dr Katerina Kormusheva",
      school: "Research School of Management",
      schoolCode: "RSM",
      position: "Lecturer and course convenor",
      focus: "Marketing, management, business information systems, pricing",
      email: "katerina.kormusheva@anu.edu.au",
      office: "Room 1066, LF Crisp Bld (26)",
      profileUrl: "https://cbe.anu.edu.au/about/staff-directory/dr-katerina-kormusheva",
      tags: ["management", "marketing", "communication"],
      linkedCourses: ["MGMT2100"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "sarbari-bordia",
      type: "academic",
      name: "Professor Sarbari Bordia",
      school: "Research School of Management",
      schoolCode: "RSM",
      position: "Professor",
      focus: "Management, business communication, international education",
      email: "sarbari.bordia@anu.edu.au",
      office: "Room 1060, LF Crisp Bld (26)",
      profileUrl: "https://cbe.anu.edu.au/about/staff-directory/professor-sarbari-bordia",
      tags: ["management", "communication", "business"],
      linkedCourses: ["MGMT2100"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "nabila-nisha",
      type: "academic",
      name: "Dr Nabila Nisha",
      school: "Research School of Management",
      schoolCode: "RSM",
      position: "Associate Lecturer",
      focus: "Marketing, consumer value creation, sharing economy",
      email: "nabila.nisha@anu.edu.au",
      office: "Room 1044, PAP Moran Bld (26B)",
      profileUrl: "https://cbe.anu.edu.au/about/staff-directory/dr-nabila-nisha",
      tags: ["marketing", "consumer behaviour", "business"],
      linkedCourses: ["MKTG2004"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "hua-deng",
      type: "academic",
      name: "Dr Hua Deng",
      school: "Research School of Finance, Actuarial Studies and Statistics",
      schoolCode: "RSFAS",
      position: "Lecturer",
      focus: "Corporate finance, corporate governance",
      email: "hua.deng@anu.edu.au",
      office: "Room 3.50, CBE Bld (26C)",
      profileUrl: "https://cbe.anu.edu.au/about/staff-directory/dr-hua-deng",
      tags: ["finance", "valuation", "corporate finance"],
      linkedCourses: [],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "xianming-zhou",
      type: "academic",
      name: "Associate Professor Xianming Zhou",
      school: "Research School of Finance, Actuarial Studies and Statistics",
      schoolCode: "RSFAS",
      position: "Associate Professor",
      focus: "Corporate governance, incentives, capital markets",
      email: "xianming.zhou@anu.edu.au",
      office: "Room 4.20, CBE Bld (26C)",
      profileUrl: "https://cbe.anu.edu.au/about/staff-directory/associate-professor-xianming-zhou",
      tags: ["finance", "corporate governance", "business"],
      linkedCourses: ["FINM3005"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "susan-bartie",
      type: "academic",
      name: "Susan Bartie",
      school: "ANU Law School",
      schoolCode: "LAW",
      position: "Senior Lecturer",
      focus: "Comparative law, environmental law, climate and health",
      email: "See ANU Law profile",
      office: "ANU Law School",
      profileUrl: "https://law.anu.edu.au/about/our-people",
      tags: ["law", "environment", "public law"],
      linkedCourses: ["LAWS2201", "LAWS6201"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "will-bateman",
      type: "academic",
      name: "Will Bateman",
      school: "ANU Law School",
      schoolCode: "LAW",
      position: "Professor",
      focus: "Administrative law, comparative public law, constitutional law",
      email: "See ANU Law profile",
      office: "ANU Law School",
      profileUrl: "https://law.anu.edu.au/about/our-people",
      tags: ["law", "public law", "constitutional"],
      linkedCourses: ["LAWS2201", "LAWS2202", "LAWS6201", "LAWS6202"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "pauline-bomball",
      type: "academic",
      name: "Pauline Bomball",
      school: "ANU Law School",
      schoolCode: "LAW",
      position: "Associate Professor",
      focus: "Labour law, law and technology, private law",
      email: "See ANU Law profile",
      office: "ANU Law School",
      profileUrl: "https://law.anu.edu.au/about/our-people",
      tags: ["law", "private law", "technology"],
      linkedCourses: ["LAWS2205", "LAWS6205"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "moeen-cheema",
      type: "academic",
      name: "Moeen Cheema",
      school: "ANU Law School",
      schoolCode: "LAW",
      position: "Associate Professor",
      focus: "Asian law, comparative public law, constitutional law",
      email: "See ANU Law profile",
      office: "ANU Law School",
      profileUrl: "https://law.anu.edu.au/about/our-people",
      tags: ["law", "asian law", "constitutional"],
      linkedCourses: ["LAWS2202", "LAWS6202"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "ruoying-chen",
      type: "academic",
      name: "Ruoying Chen",
      school: "ANU Law School",
      schoolCode: "LAW",
      position: "Senior Lecturer",
      focus: "Administrative law, Asian law, commercial and corporate law",
      email: "See ANU Law profile",
      office: "ANU Law School",
      profileUrl: "https://law.anu.edu.au/about/our-people",
      tags: ["law", "administrative law", "corporate"],
      linkedCourses: ["LAWS2201", "LAWS2207", "LAWS6201", "LAWS6203"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "jason-chin",
      type: "academic",
      name: "Jason Chin",
      school: "ANU Law School",
      schoolCode: "LAW",
      position: "Associate Professor",
      focus: "Evidence, law science and technology, environment and climate health",
      email: "See ANU Law profile",
      office: "ANU Law School",
      profileUrl: "https://law.anu.edu.au/about/our-people",
      tags: ["law", "evidence", "technology"],
      linkedCourses: ["LAWS2208", "LAWS6207"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "donald-butler",
      type: "academic",
      name: "Donald Butler",
      school: "ANU Law School",
      schoolCode: "LAW",
      position: "Professor",
      focus: "Environmental law",
      email: "See ANU Law profile",
      office: "ANU Law School",
      profileUrl: "https://law.anu.edu.au/about/our-people",
      tags: ["law", "environment"],
      linkedCourses: ["LAWS4281", "LAWS6281"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    },
    {
      id: "saule-burkitbayeva",
      type: "academic",
      name: "Saule Burkitbayeva",
      school: "ANU Law School",
      schoolCode: "LAW",
      position: "Senior Lecturer",
      focus: "Climate change and climate finance, environmental law, international economic law",
      email: "See ANU Law profile",
      office: "ANU Law School",
      profileUrl: "https://law.anu.edu.au/about/our-people",
      tags: ["law", "climate", "international"],
      linkedCourses: ["LAWS2209", "LAWS2214", "LAWS6250"],
      reviewMetrics: ["Clarity", "Support", "Engagement"]
    }
  ],
  courses: [
    {
      id: "ECON1101",
      type: "course",
      code: "ECON1101",
      name: "Microeconomics 1",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["First Semester", "Second Semester", "Spring Session"],
      conveners: ["ralf-steinhauser"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON1101",
      summary: "Introductory microeconomics covering supply and demand, consumer and firm choice, market structure, and government intervention.",
      tags: ["economics", "first-year", "core"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON1102",
      type: "course",
      code: "ECON1102",
      name: "Macroeconomics 1",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["First Semester", "Second Semester"],
      conveners: ["timo-henckel", "elena-capatina"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON1102",
      summary: "Introductory macroeconomics on inflation, unemployment, output, growth, exchange rates, and policy responses.",
      tags: ["economics", "macro", "core"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "EMET1001",
      type: "course",
      code: "EMET1001",
      name: "Foundations of Economic and Financial Models",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["First Semester"],
      conveners: ["tina-kao"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/EMET1001",
      summary: "Mathematical foundations for economics, business, and finance including calculus, optimisation, matrix algebra, and applications.",
      tags: ["econometrics", "quantitative", "foundations"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON2014",
      type: "course",
      code: "ECON2014",
      name: "Managerial Economics",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["First Semester"],
      conveners: ["marina-iskhakova"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON2014",
      summary: "Applied economics for managerial decision-making, focusing on firms, incentives, and practical economic reasoning.",
      tags: ["economics", "business", "management"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON2101",
      type: "course",
      code: "ECON2101",
      name: "Microeconomics 2",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["First Semester", "Second Semester"],
      conveners: ["james-taylor", "rohan-pitchford"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON2101",
      summary: "Intermediate microeconomics on consumer and producer theory, market efficiency, and problem-solving through tutorials.",
      tags: ["economics", "micro", "intermediate"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON2125",
      type: "course",
      code: "ECON2125",
      name: "Optimisation for Economics and Financial Economics",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["First Semester", "Second Semester"],
      conveners: ["james-taylor", "ruitian-lang"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON2125",
      summary: "A mathematically rigorous optimisation course for economics and financial economics students, grounded in theory and proofs.",
      tags: ["economics", "maths", "financial economics"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON3101",
      type: "course",
      code: "ECON3101",
      name: "Microeconomics 3",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["First Semester"],
      conveners: ["kieron-meagher"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON3101",
      summary: "Advanced microeconomics with deeper theoretical rigour and applications to policy, uncertainty, and information.",
      tags: ["economics", "advanced", "theory"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON8069",
      type: "course",
      code: "ECON8069",
      name: "Business Economics",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "PGRD",
      terms: ["First Semester", "Second Semester"],
      conveners: ["marina-iskhakova", "ruitian-lang"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON8069",
      summary: "Graduate business economics covering microeconomic and macroeconomic concepts for understanding the business environment.",
      tags: ["economics", "business", "postgraduate"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "MGMT2100",
      type: "course",
      code: "MGMT2100",
      name: "Communication for Business",
      school: "Research School of Management",
      schoolCode: "RSM",
      level: "UGRD",
      terms: ["First Semester", "Second Semester"],
      conveners: ["katerina-kormusheva", "sarbari-bordia"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/MGMT2100",
      summary: "Business communication fundamentals with emphasis on writing, presentation, interpersonal communication, and applied theory.",
      tags: ["business", "management", "communication"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "MGMT3015",
      type: "course",
      code: "MGMT3015",
      name: "Corporate Strategy",
      school: "Research School of Management",
      schoolCode: "RSM",
      level: "UGRD",
      terms: ["First Semester"],
      conveners: ["alexander-eapen"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/MGMT3015",
      summary: "Strategic management course on formulation and implementation of strategy and the drivers of business success or failure.",
      tags: ["business", "strategy", "management"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "MKTG2004",
      type: "course",
      code: "MKTG2004",
      name: "Introduction to Marketing",
      school: "Research School of Management",
      schoolCode: "RSM",
      level: "UGRD",
      terms: ["First Semester", "Second Semester"],
      conveners: ["nabila-nisha"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/MKTG2004",
      summary: "Broad marketing introduction covering consumer insight, market positioning, and the core ideas behind marketing practice.",
      tags: ["business", "marketing", "undergraduate"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "FINM3005",
      type: "course",
      code: "FINM3005",
      name: "Corporate Valuation",
      school: "Research School of Finance, Actuarial Studies and Statistics",
      schoolCode: "RSFAS",
      level: "UGRD",
      terms: ["First Semester", "Second Semester"],
      conveners: ["xianming-zhou"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/FINM3005",
      summary: "Finance course focused on valuation methods, capital markets, and analysing firms through a corporate finance lens.",
      tags: ["business", "finance", "valuation"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "STAT1008",
      type: "course",
      code: "STAT1008",
      name: "Quantitative Research Methods",
      school: "Supporting ANU course",
      schoolCode: "STAT",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/STAT1008",
      summary: "Included in the 2026 Bachelor of Economics requirements as a quantitative foundation course.",
      tags: ["statistics", "becon", "core"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON1100",
      type: "course",
      code: "ECON1100",
      name: "Economics I (H)",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON1100",
      summary: "Honours-stream first-year economics course listed in the 2026 Bachelor of Economics requirements.",
      tags: ["economics", "honours", "becon"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON2016",
      type: "course",
      code: "ECON2016",
      name: "Economics II (H)",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON2016",
      summary: "Honours-stream second-year economics course listed in the 2026 Bachelor of Economics requirements.",
      tags: ["economics", "honours", "becon"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON2102",
      type: "course",
      code: "ECON2102",
      name: "Macroeconomics 2",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON2102",
      summary: "Intermediate macroeconomics course included in the 2026 Bachelor of Economics structure.",
      tags: ["economics", "macro", "becon"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON3102",
      type: "course",
      code: "ECON3102",
      name: "Macroeconomics 3",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON3102",
      summary: "Advanced macroeconomics core course in the 2026 Bachelor of Economics.",
      tags: ["economics", "macro", "advanced"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "EMET2007",
      type: "course",
      code: "EMET2007",
      name: "Econometrics I: Econometric Methods",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/EMET2007",
      summary: "Core econometrics course required for BEcon and listed in the Econometrics minor.",
      tags: ["econometrics", "becon", "core"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "CBEA2001",
      type: "course",
      code: "CBEA2001",
      name: "Indigenous Perspectives in Business and Economics",
      school: "ANU College of Business and Economics",
      schoolCode: "CBE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/CBEA2001",
      summary: "Transdisciplinary course listed in the 2026 Bachelor of Economics requirements.",
      tags: ["cbe", "transdisciplinary", "becon"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECHI1006",
      type: "course",
      code: "ECHI1006",
      name: "The Australian Economy: Past and Present",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECHI1006",
      summary: "Economic history course listed in the 2026 Bachelor of Economics requirements.",
      tags: ["economic history", "becon", "transdisciplinary"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECHI3009",
      type: "course",
      code: "ECHI3009",
      name: "World Economy Since 1800",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECHI3009",
      summary: "Economic history course appearing in the 2026 Bachelor of Economics lists.",
      tags: ["economic history", "becon", "advanced"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON2108",
      type: "course",
      code: "ECON2108",
      name: "Japanese Economy and Political Economy",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON2108",
      summary: "Listed in the 2026 Bachelor of Economics transdisciplinary and restricted course lists.",
      tags: ["economics", "political economy", "becon"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON2900",
      type: "course",
      code: "ECON2900",
      name: "Development Poverty and Famine",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON2900",
      summary: "Development-focused course listed in the 2026 Bachelor of Economics requirements.",
      tags: ["economics", "development", "becon"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON3004",
      type: "course",
      code: "ECON3004",
      name: "Health Economics",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON3004",
      summary: "Health economics elective listed in the 2026 Bachelor of Economics requirements.",
      tags: ["economics", "health", "becon"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON3006",
      type: "course",
      code: "ECON3006",
      name: "Financial Economics",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON3006",
      summary: "Financial economics course listed in the 2026 Bachelor of Economics requirements.",
      tags: ["economics", "finance", "becon"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON3023",
      type: "course",
      code: "ECON3023",
      name: "Economic Policy Issues",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON3023",
      summary: "Policy-focused economics course listed in the 2026 Bachelor of Economics requirements.",
      tags: ["economics", "policy", "becon"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON3057",
      type: "course",
      code: "ECON3057",
      name: "Industrial Organisation",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON3057",
      summary: "Upper-level economics course listed in the Bachelor of Economics and SBEC minor.",
      tags: ["economics", "industry", "strategy"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON3100",
      type: "course",
      code: "ECON3100",
      name: "Economics 3 (H)",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON3100",
      summary: "Honours-stream advanced economics course listed in the 2026 Bachelor of Economics.",
      tags: ["economics", "honours", "advanced"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON3103",
      type: "course",
      code: "ECON3103",
      name: "International Economics",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON3103",
      summary: "Upper-level international economics elective in the 2026 Bachelor of Economics list.",
      tags: ["economics", "international", "becon"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON3127",
      type: "course",
      code: "ECON3127",
      name: "Computational Methods in Economics",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON3127",
      summary: "Computational economics course listed in the 2026 Bachelor of Economics requirements.",
      tags: ["economics", "computational", "becon"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON3128",
      type: "course",
      code: "ECON3128",
      name: "Resource and Environmental Economics",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON3128",
      summary: "Resource and environmental economics elective listed in the 2026 Bachelor of Economics.",
      tags: ["economics", "environment", "becon"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON3181",
      type: "course",
      code: "ECON3181",
      name: "Competition Policy and Regulation",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON3181",
      summary: "Competition policy course listed in the 2026 Bachelor of Economics and SBEC minor pages.",
      tags: ["economics", "regulation", "strategy"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON2009",
      type: "course",
      code: "ECON2009",
      name: "Labour Economics and Industrial Relations Policy",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON2009",
      summary: "Labour economics elective listed in the 2026 Bachelor of Economics restricted course list.",
      tags: ["economics", "labour", "policy"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON2026",
      type: "course",
      code: "ECON2026",
      name: "Money and Banking",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON2026",
      summary: "Monetary economics course listed in the 2026 Bachelor of Economics restricted course list.",
      tags: ["economics", "banking", "macro"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON2091",
      type: "course",
      code: "ECON2091",
      name: "The Economy, Politics and the State",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON2091",
      summary: "Political economy course listed in the 2026 Bachelor of Economics restricted course list.",
      tags: ["economics", "politics", "state"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON2131",
      type: "course",
      code: "ECON2131",
      name: "Public Sector Economics",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON2131",
      summary: "Public economics course listed in the 2026 Bachelor of Economics restricted course list.",
      tags: ["economics", "public economics", "policy"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON2142",
      type: "course",
      code: "ECON2142",
      name: "Strategic Thinking (H)",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON2142",
      summary: "Honours-stream strategic thinking course referenced on the 2026 SBEC minor page.",
      tags: ["economics", "game theory", "honours"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "ECON3157",
      type: "course",
      code: "ECON3157",
      name: "Industrial Organ (H)",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/ECON3157",
      summary: "Honours-stream industrial organisation alternative referenced on the 2026 SBEC minor page.",
      tags: ["economics", "industry", "honours"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "EMET3004",
      type: "course",
      code: "EMET3004",
      name: "Econometrics II: Econometric Modelling",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/EMET3004",
      summary: "Upper-level econometrics course listed in the 2026 BEcon and EMET minor pages.",
      tags: ["econometrics", "modelling", "becon"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "EMET3006",
      type: "course",
      code: "EMET3006",
      name: "Applied Micro-econometrics",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/EMET3006",
      summary: "Upper-level econometrics course listed in the 2026 BEcon and EMET minor pages.",
      tags: ["econometrics", "microeconometrics", "becon"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "EMET3007",
      type: "course",
      code: "EMET3007",
      name: "Business and Economic Forecasting",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/EMET3007",
      summary: "Forecasting course listed in the 2026 BEcon and EMET minor pages.",
      tags: ["econometrics", "forecasting", "business"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "EMET3008",
      type: "course",
      code: "EMET3008",
      name: "Applied Macro and Financial Econometrics",
      school: "Research School of Economics",
      schoolCode: "RSE",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/EMET3008",
      summary: "Macro and financial econometrics course listed in the 2026 BEcon and EMET minor pages.",
      tags: ["econometrics", "macro", "finance"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS1201",
      type: "course",
      code: "LAWS1201",
      name: "Foundations of Australian Law",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS1201",
      summary: "Compulsory course on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "llb", "core"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS1202",
      type: "course",
      code: "LAWS1202",
      name: "Lawyers, Justice and Ethics",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS1202",
      summary: "Compulsory course on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "ethics", "llb"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS1203",
      type: "course",
      code: "LAWS1203",
      name: "Torts",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS1203",
      summary: "Compulsory course on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "torts", "llb"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS1204",
      type: "course",
      code: "LAWS1204",
      name: "Contracts",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS1204",
      summary: "Compulsory course on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "contracts", "llb"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS1205",
      type: "course",
      code: "LAWS1205",
      name: "Australian Public Law",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS1205",
      summary: "Compulsory course on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "public law", "llb"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS1206",
      type: "course",
      code: "LAWS1206",
      name: "Criminal Law and Procedure",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS1206",
      summary: "Compulsory course on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "criminal law", "llb"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS2201",
      type: "course",
      code: "LAWS2201",
      name: "Administrative Law",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: ["susan-bartie", "will-bateman", "ruoying-chen"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS2201",
      summary: "Compulsory course on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "administrative law", "llb"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS2202",
      type: "course",
      code: "LAWS2202",
      name: "Commonwealth Constitutional Law",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: ["will-bateman", "moeen-cheema"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS2202",
      summary: "Compulsory course on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "constitutional law", "llb"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS2203",
      type: "course",
      code: "LAWS2203",
      name: "Corporations Law",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: ["ruoying-chen"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS2203",
      summary: "Compulsory course on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "corporations", "llb"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS2204",
      type: "course",
      code: "LAWS2204",
      name: "Property",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS2204",
      summary: "Compulsory course on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "property", "llb"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS2205",
      type: "course",
      code: "LAWS2205",
      name: "Equity and Trusts",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: ["pauline-bomball"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS2205",
      summary: "Compulsory course on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "equity", "llb"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS2207",
      type: "course",
      code: "LAWS2207",
      name: "Evidence",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: ["jason-chin", "ruoying-chen"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS2207",
      summary: "Compulsory course on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "evidence", "llb"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS2244",
      type: "course",
      code: "LAWS2244",
      name: "Litigation and Dispute Management",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS2244",
      summary: "Compulsory course on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "litigation", "llb"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS2248",
      type: "course",
      code: "LAWS2248",
      name: "Legal Research and Writing",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS2248",
      summary: "Compulsory course on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "research", "llb"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS2249",
      type: "course",
      code: "LAWS2249",
      name: "Legal Theory",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS2249",
      summary: "Compulsory course on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "theory", "llb"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS2250",
      type: "course",
      code: "LAWS2250",
      name: "International Law",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: ["saule-burkitbayeva"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS2250",
      summary: "Compulsory course on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "international law", "llb"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS4010",
      type: "course",
      code: "LAWS4010",
      name: "Jessup Moot",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS4010",
      summary: "Capstone course named on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "capstone", "moot"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS4213",
      type: "course",
      code: "LAWS4213",
      name: "Law Internship (Honours)",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS4213",
      summary: "Capstone course named on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "capstone", "internship"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS4218",
      type: "course",
      code: "LAWS4218",
      name: "Community Law Clinic",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS4218",
      summary: "Capstone course named on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "clinic", "capstone"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS4230",
      type: "course",
      code: "LAWS4230",
      name: "Law and Development Clinic",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS4230",
      summary: "Capstone course named on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "clinic", "development"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS4256",
      type: "course",
      code: "LAWS4256",
      name: "Youth Law Clinic",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS4256",
      summary: "Capstone course named on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "clinic", "youth"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS4262",
      type: "course",
      code: "LAWS4262",
      name: "International Law Clinic",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS4262",
      summary: "Capstone course named on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "clinic", "international"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS4299",
      type: "course",
      code: "LAWS4299",
      name: "Prison Legal Literacy Clinic",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS4299",
      summary: "Capstone course named on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "clinic", "justice"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS4300",
      type: "course",
      code: "LAWS4300",
      name: "Final Honours Grade",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS4300",
      summary: "Named on the 2026 Bachelor of Laws (Honours) page for honours recording.",
      tags: ["law", "honours", "llb"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS4302",
      type: "course",
      code: "LAWS4302",
      name: "International Humanitarian Law Clinic",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS4302",
      summary: "Capstone course named on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "clinic", "international"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS4315",
      type: "course",
      code: "LAWS4315",
      name: "Indigenous Community Legal Clinic",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS4315",
      summary: "Capstone course named on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "clinic", "indigenous"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS4601",
      type: "course",
      code: "LAWS4601",
      name: "Environmental Law Clinic",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: ["donald-butler"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS4601",
      summary: "Capstone course named on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "clinic", "environment"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS4700",
      type: "course",
      code: "LAWS4700",
      name: "Law Honours Thesis",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "UGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS4700",
      summary: "Capstone course named on the 2026 Bachelor of Laws (Honours) page.",
      tags: ["law", "honours", "thesis"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6101",
      type: "course",
      code: "LAWS6101",
      name: "Foundations of Australian Law",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6101",
      summary: "Compulsory course on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "core"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6102",
      type: "course",
      code: "LAWS6102",
      name: "Lawyers, Justice and Ethics",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6102",
      summary: "Compulsory course on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "ethics"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6103",
      type: "course",
      code: "LAWS6103",
      name: "Torts",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6103",
      summary: "Compulsory course on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "torts"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6104",
      type: "course",
      code: "LAWS6104",
      name: "Contracts",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6104",
      summary: "Compulsory course on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "contracts"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6105",
      type: "course",
      code: "LAWS6105",
      name: "Australian Public Law",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6105",
      summary: "Compulsory course on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "public law"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6106",
      type: "course",
      code: "LAWS6106",
      name: "Criminal Law and Procedure",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6106",
      summary: "Compulsory course on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "criminal law"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6201",
      type: "course",
      code: "LAWS6201",
      name: "Administrative Law",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: ["susan-bartie", "will-bateman", "ruoying-chen"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6201",
      summary: "Compulsory course on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "administrative law"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6202",
      type: "course",
      code: "LAWS6202",
      name: "Commonwealth Constitutional Law",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: ["will-bateman", "moeen-cheema"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6202",
      summary: "Compulsory course on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "constitutional law"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6203",
      type: "course",
      code: "LAWS6203",
      name: "Corporations Law",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: ["ruoying-chen"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6203",
      summary: "Compulsory course on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "corporations"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6204",
      type: "course",
      code: "LAWS6204",
      name: "Property",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6204",
      summary: "Compulsory course on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "property"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6205",
      type: "course",
      code: "LAWS6205",
      name: "Equity and Trusts",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: ["pauline-bomball"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6205",
      summary: "Compulsory course on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "equity"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6207",
      type: "course",
      code: "LAWS6207",
      name: "Evidence",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: ["jason-chin"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6207",
      summary: "Compulsory course on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "evidence"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6244",
      type: "course",
      code: "LAWS6244",
      name: "Litigation and Dispute Management",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6244",
      summary: "Compulsory course on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "litigation"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6249",
      type: "course",
      code: "LAWS6249",
      name: "Legal Theory",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6249",
      summary: "Compulsory course on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "theory"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6250",
      type: "course",
      code: "LAWS6250",
      name: "International Law",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: ["saule-burkitbayeva"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6250",
      summary: "Compulsory course on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "international law"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6010",
      type: "course",
      code: "LAWS6010",
      name: "Jessup Moot",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6010",
      summary: "Capstone course named on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "capstone"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6230",
      type: "course",
      code: "LAWS6230",
      name: "Law Internship (Capstone)",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6230",
      summary: "Capstone course named on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "internship"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6267",
      type: "course",
      code: "LAWS6267",
      name: "Youth Law Clinic",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6267",
      summary: "Capstone course named on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "clinic"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6268",
      type: "course",
      code: "LAWS6268",
      name: "Community Law Clinic",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6268",
      summary: "Capstone course named on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "clinic"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6278",
      type: "course",
      code: "LAWS6278",
      name: "Indigenous Community Legal Clinic",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6278",
      summary: "Capstone course named on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "clinic"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6281",
      type: "course",
      code: "LAWS6281",
      name: "Environmental Law Clinic",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: ["donald-butler"],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6281",
      summary: "Capstone course named on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "clinic"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6301",
      type: "course",
      code: "LAWS6301",
      name: "Law and Development Clinic",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6301",
      summary: "Capstone course named on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "clinic"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6302",
      type: "course",
      code: "LAWS6302",
      name: "International Law Clinic",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6302",
      summary: "Capstone course named on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "clinic"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6304",
      type: "course",
      code: "LAWS6304",
      name: "Prison Legal Literacy Clinic",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6304",
      summary: "Capstone course named on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "clinic"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6307",
      type: "course",
      code: "LAWS6307",
      name: "Legal Education for True Justice: Indigenous Perspectives and Deep Listening on Country",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6307",
      summary: "Capstone course named on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "indigenous"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS6700",
      type: "course",
      code: "LAWS6700",
      name: "Juris Doctor Capstone Project",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS6700",
      summary: "Capstone course named on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "capstone"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS8301",
      type: "course",
      code: "LAWS8301",
      name: "Postgraduate Research Dissertation",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS8301",
      summary: "Capstone course named on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "research"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    },
    {
      id: "LAWS8430",
      type: "course",
      code: "LAWS8430",
      name: "Law Internship",
      school: "ANU Law School",
      schoolCode: "LAW",
      level: "PGRD",
      terms: ["See ANU course page"],
      conveners: [],
      handbookUrl: "https://programsandcourses.anu.edu.au/course/LAWS8430",
      summary: "Capstone course named on the 2026 Juris Doctor page.",
      tags: ["law", "jd", "internship"],
      reviewMetrics: ["Teaching quality", "Workload fairness", "Assessment design"]
    }
  ],
  seedReviews: [
    {
      id: "seed-1",
      itemId: "ECON1101",
      itemType: "course",
      author: "Anon",
      createdAt: "2026-03-02",
      overall: 4,
      metricA: 4,
      metricB: 3,
      metricC: 4,
      tags: ["great intro", "clear tutorials"],
      comment: "Good first economics course if you keep up weekly. Tutorial questions were the main thing that made the theory click."
    },
    {
      id: "seed-2",
      itemId: "ECON2125",
      itemType: "course",
      author: "Quant student",
      createdAt: "2026-03-18",
      overall: 4,
      metricA: 4,
      metricB: 2,
      metricC: 3,
      tags: ["math-heavy", "proofs"],
      comment: "Interesting but definitely not a casual elective. It rewards consistent practice more than last-minute study."
    },
    {
      id: "seed-3",
      itemId: "MGMT2100",
      itemType: "course",
      author: "Anon",
      createdAt: "2026-02-27",
      overall: 4,
      metricA: 4,
      metricB: 4,
      metricC: 3,
      tags: ["practical", "presentation skills"],
      comment: "Useful if you actually want to get better at business writing and speaking, not just collect a grade."
    },
    {
      id: "seed-4",
      itemId: "timo-henckel",
      itemType: "academic",
      author: "Second year",
      createdAt: "2026-03-10",
      overall: 5,
      metricA: 5,
      metricB: 4,
      metricC: 5,
      tags: ["engaging", "policy examples"],
      comment: "Explains macro in a way that makes the models feel connected to real policy debates."
    },
    {
      id: "seed-5",
      itemId: "james-taylor",
      itemType: "academic",
      author: "Anon",
      createdAt: "2026-03-15",
      overall: 4,
      metricA: 4,
      metricB: 3,
      metricC: 4,
      tags: ["rigorous", "theory-first"],
      comment: "Strong if you like formal reasoning. Go to class ready to think, not just memorise."
    },
    {
      id: "seed-6",
      itemId: "nabila-nisha",
      itemType: "academic",
      author: "Marketing major",
      createdAt: "2026-03-20",
      overall: 4,
      metricA: 4,
      metricB: 4,
      metricC: 4,
      tags: ["approachable", "structured"],
      comment: "The material felt well organised and the class atmosphere was more welcoming than expected."
    }
  ]
};
